#!/usr/bin/env php
<?php

//ini_set('display_errors', '0');
error_reporting(E_ALL);

try {
	require 'vendor/diskerror/autoload/autoload.php';

	$cli = new Service\Application\Cli();
	$cli->run($argv);
}
catch (Phalcon\Cli\Dispatcher\Exception $e) {
	fwrite(STDERR, $e->getMessage());
}
catch (Throwable $t) {
	fwrite(STDERR, $t);
}
