#!/usr/bin/env php
<?php

ini_set('display_errors', '1');
error_reporting(E_ALL);

define('BASE_PATH', __DIR__);

/**
 * Convert all errors into ErrorExceptions
 */
set_error_handler(
	function($severity, $errstr, $errfile, $errline) {
		throw new ErrorException($errstr, 1, $severity, $errfile, $errline);
	},
	E_ERROR
);

try {
	require 'vendor/autoload.php';
	require 'app/Loader.php';
	Loader::register([__DIR__ . '/app/tasks/']);

	$cli = new Service\Application\Cli(__DIR__);
	$cli->init();
	$cli->run($argv);
}
catch (Throwable $t) {
	fwrite(STDERR, $t . PHP_EOL);
}
