#!/usr/bin/env php
<?php

//ini_set('display_errors', '0');
//error_reporting(E_ERROR);

define('BASE_PATH', __DIR__);

require 'vendor/autoload.php';

try {
	$cli = new Service\Application\Cli(__DIR__);
	$cli->run($argv);
}
catch (Phalcon\Cli\Dispatcher\Exception $e) {
	fwrite(STDERR, $e->getMessage() . PHP_EOL);
}
catch (Throwable $t) {
	fwrite(STDERR, $t . PHP_EOL);
}
