<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Implant Direct Middleware</title>

    <link rel="stylesheet" type="text/css" href="/css/style.css" />
    <link rel="stylesheet" type="text/css" href="/css/bootstrap-theme.min.css" />
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css" />

    <script async src='/js/jquery-3.1.0.min.js'></script>
    <script async src='/js/bootstrap.min.js'></script>
    <?php $this->assets->outputJs() ?>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
                <img src="/img/logo.png" height="28"/> Implant Direct Middleware
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">Home</a></li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <?= $this->getContent(); ?>
    <hr>
    <footer>
        <p>&copy; 2018 by Implant Direct. All rights reserved.</p>
    </footer>
</div>
</body>
</html>
